title: Josh Archibald
description: >-
  Josh Archibald is a Harvard junior studying computer science.
baseurl: ""
url: "https://www.josharchibald.com"
lang: "en-us"
image: "https://www.josharchibald.com/assets/josh.jpg"
plugins:
  - jekyll-paginate
paginate: 5
paginate_path: "/blog/:num/"
permalink: /blog/:year/:month/:title
collections:
  category:
    output: true
defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
