title: Josh Archibald
description: >-
  Josh Archibald is a Harvard sophomore studying computer science.
baseurl: ""
url: "https://www.josharchibald.com"
lang: "en-us"
image: "https://www.josharchibald.com/assets/josh.jpg"